name: CI (React + Vite, npm, Node 22.17)

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22.17 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build
